# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('honor', models.TextField(max_length=1000)),
                ('recurrence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=40, verbose_name='LastName')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('interest', models.ManyToManyField(to='mainsite.Catagory')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Profolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('catagory', models.ManyToManyField(to='mainsite.Catagory')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='profolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Profolio'),
        ),
    ]
