# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profolio',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
