# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20170218_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='profolio',
            old_name='catagory',
            new_name='category',
        ),
    ]
