# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_donation_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recurrence',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
